/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppEmpleadosIndexRouteImport } from './routes/_app/empleados.index'
import { Route as AppEmpleadosIdRouteImport } from './routes/_app/empleados.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpleadosIndexRoute = AppEmpleadosIndexRouteImport.update({
  id: '/empleados/',
  path: '/empleados/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpleadosIdRoute = AppEmpleadosIdRouteImport.update({
  id: '/empleados/$id',
  path: '/empleados/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/empleados/$id': typeof AppEmpleadosIdRoute
  '/empleados/': typeof AppEmpleadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/empleados/$id': typeof AppEmpleadosIdRoute
  '/empleados': typeof AppEmpleadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/empleados/$id': typeof AppEmpleadosIdRoute
  '/_app/empleados/': typeof AppEmpleadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/empleados/$id' | '/empleados/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/empleados/$id' | '/empleados'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/empleados/$id'
    | '/_app/empleados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empleados/': {
      id: '/_app/empleados/'
      path: '/empleados'
      fullPath: '/empleados/'
      preLoaderRoute: typeof AppEmpleadosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empleados/$id': {
      id: '/_app/empleados/$id'
      path: '/empleados/$id'
      fullPath: '/empleados/$id'
      preLoaderRoute: typeof AppEmpleadosIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmpleadosIdRoute: typeof AppEmpleadosIdRoute
  AppEmpleadosIndexRoute: typeof AppEmpleadosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppEmpleadosIdRoute: AppEmpleadosIdRoute,
  AppEmpleadosIndexRoute: AppEmpleadosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
